histogram/skeleton/cards
js-tasks-ru/htmlcss-20210513_liza8 pull request #4
Opened 2021-05-27 09:25 UTC by korcha

New branch with histogram/skeleton/cards

2021-05-27 09:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-28 13:45 UTC, GSemikozov requested changes

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.page{
этот класс добавлен как враппер для блока - все врапперы должны быть либо другими блоками, либо если они точечные и применяются лишь для более красивого отображения в html файле с решением - то их надо перемещать прямиков в файл с этим решением ;)

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width:auto;
ширину у inline-flex'а и так будет auto ;)

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
высоту фиксировать не обязательно (например, тайтл у нас будет не в 1 строку, а сразу в 3 - вот такой вот длинный; тогда наш внутренний контент вылезет за пределы блока гостограммы)

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width:100%;
чтобы явно не задавать width: 100%, можно чуть выше сделать не inline-flex, а flex

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    color:#4263EB;
есть ли такой цвет в переменных? если да, то заберем оттуда

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-self: flex-end;
вместо space-between у родителя и align-self: flex-end здесь (работает, кстати, потому, что мы задали фиксированную высоту, а элементы внутри блока совокупно по высоте меньше, поэтому есть возможность "раздвинуть" блоки) - лучше просто удалить эти свойство вместе с фиксированной высотой блока, и вместо этого задать у .histograme__content отступ свверху в 40px как в дизайне.

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.page{
опять этот злосчастный .block в файле другого блока))

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    min-width: 579px;
слишком большая минимальная ширина, на мобилке не влезет. Советую ее вообще убрать, пусть ширина будет 100% по умолчанию, и скелетон растягивается по родителю

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 192px;
высоту тоже не стоит фиксировать, эту строку можно удалить

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 80px;
а почему ширина больше чем высота? тогда получится не круг, а овал))

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 80px;
наверное, здесь еще должен был быть включен отступ. Но отступ задается через gap у родителя, так что все ок, можно сделать нормальный круг

2021-05-28 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +span{
селектором тегов не должно быть в БЭМ-блоке, поэтому стоит заменить на класс, например, с учетом модификаторов, так - `.skeleton__text-line_long { width: 60%; }` и `.skeleton__text-line_short { width: 40%; }`, `.skeleton__text-line { display: block;    height: 20px;    width:100%;    background: linear-gradient(92.51deg, #DDE2E5 6.44%, #E2E6E8 38.47%, #F3F5F5 56.48%, #E3E7EA 77.5%, #DDE2E5 102.52%);}`

2021-05-28 13:45 UTC, GSemikozov commented on assets/css/main.css
> +.block-page{
это будет общий контейнер? если да, и раз уж он не определен в отдельной блоке, тогда можно дать ему более понятное имя - `.container`

2021-05-30 17:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 17:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 17:55 UTC, korcha commented
Готово, отправила фиксы

2021-05-31 12:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-01 10:35 UTC, korcha commented on assets/css/main.css
> +.block-page{
Готово, отправила

2021-06-01 10:41 UTC, korcha commented on 04-lection2/01-histogram/histogram.css
> +.page{
готово

2021-06-01 10:41 UTC, korcha commented on 04-lection2/01-histogram/histogram.css
> +    width:auto;
готово

2021-06-01 10:41 UTC, korcha commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
готово

2021-06-01 10:41 UTC, korcha commented on 04-lection2/01-histogram/histogram.css
> +    width:100%;
готово

2021-06-01 10:43 UTC, korcha commented on 04-lection2/02-skeleton/skeleton.css
> +    min-width: 579px;
готово

2021-06-01 10:43 UTC, korcha commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 80px;
тогда оставила как есть

2021-06-01 10:43 UTC, korcha commented on 04-lection2/02-skeleton/skeleton.css
> +span{
прописала

2021-06-01 10:45 UTC, korcha commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 192px;
готово

2021-06-01 10:45 UTC, korcha commented on 04-lection2/01-histogram/histogram.css
> +    color:#4263EB;
добавила

2021-06-01 11:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-01 11:19 UTC, GSemikozov approved these changes

2021-06-01 11:19 UTC, merged