tooltip/modal/input
js-tasks-ru/htmlcss-20210513_liza8 pull request #6
Opened 2021-06-07 15:52 UTC by korcha

Tooltip/Modal/Input

2021-06-07 15:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-08 14:31 UTC, GSemikozov requested changes

2021-06-08 14:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
здесь важно делать через fixed - absolute привязывается к любому ближайшему соседу с position relative | absolute, что можно нам изрядно подпортить картину) а fixed позиционирует относительно окна браузера

2021-06-08 14:31 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__normal::-webkit-input-placeholder {
`.input__normal, .input__invalid, .input__success, input__focus` - это все-таки не элементы а модификаторы, поэтому - `.input_normal, .input_invalid, .input_success, input_focus`. Вместо input_focus кстати говоря желательно использовать встроенныq псевдокласс :focus

2021-06-08 14:31 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    top:50%;
в дизайне там top и right по 18px)

2021-06-08 14:31 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    top:50%;
если хотим четко по середине любую иконку - `top: 50%; right: 18px; transform: translate(0, -50%)`

2021-06-08 14:58 UTC, korcha commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
готово

2021-06-08 15:00 UTC, korcha commented on 07-lection5/04-input/input.css
> +.input__normal::-webkit-input-placeholder {
а можно  модификаторы я через .input--normal буду отмечать (двойной дефис)?

2021-06-08 17:08 UTC, korcha commented on 07-lection5/04-input/input.css
> +    top:50%;
right поправила, а вот по поводу top вопрос.  input__icon   позиционируется относительно родителя блока .input,  а не по .input__field. Поэтому , если я использую transform: translate(0, -50%) иконка находится выше. Как сделать, чтобы позиционирование было относительно <input>?

2021-06-08 17:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-08 17:16 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__normal::-webkit-input-placeholder {
конечно

2021-06-08 17:16 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    top:50%;
ааа... тогда нужно сделать дополнительный враппер который обернет инпут и иконку, и будет иметь position: relative)

2021-06-08 17:17 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    top:50%;
например, `.input__filed-wrapper`

2021-06-08 17:20 UTC, korcha commented on 07-lection5/04-input/input.css
> +    top:50%;
Поняла, сделала

2021-06-08 17:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-08 17:23 UTC, GSemikozov approved these changes

2021-06-08 17:23 UTC, merged