Branch 7
js-tasks-ru/htmlcss-20210513_liza8 pull request #7
Opened 2021-06-09 14:22 UTC by korcha

checkbox/radio/toggle/tabs

2021-06-09 14:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-09 16:22 UTC, GSemikozov requested changes

2021-06-09 16:22 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    margin-top:20px;
внешние отступы самому блоку не задаем, можно только через родительский блок, в который будем встраивать чекбокс

2021-06-09 16:22 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    width: 0px;
еще инпут может фокусироваться (добавляется outline), а некоторые браузеры или стили проектов могут болаблять свои отступы - поэтому чтобы избежать других возможных коллизий, желательно еще задать `outline: none; position: absolute; pointer-events: none; opacity: 0;`

2021-06-09 16:22 UTC, GSemikozov commented on 07-lection5/01-checkbox/index.html
> +        .tab{
тут и ниже - как-то многовато переопределяющих стилей для табов, особенно с учетом того что их мы не сможем переиспользовать, а у нас ведь есть табы еще и на странице Компонента)

2021-06-09 16:22 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    border:3px solid var(--white);
а внешний бордер точно будет при этом синим?

2021-06-09 16:22 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    width: 26px;
тут по идее должно быть 24

2021-06-09 16:22 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    top:0;
по идее 2px

2021-06-09 16:22 UTC, GSemikozov commented on components/tabs/tab.css
> +    width:0px;
тот же принцип прятать который описан в начале ПР для чекбокса

2021-06-09 20:30 UTC, korcha commented on 07-lection5/01-checkbox/checkbox.css
> +    margin-top:20px;
Поправила

2021-06-09 20:30 UTC, korcha commented on 07-lection5/01-checkbox/checkbox.css
> +    width: 0px;
поправила

2021-06-09 20:31 UTC, korcha commented on 07-lection5/01-checkbox/index.html
> +        .tab{
это я случайно не в том index.html работала, убрала

2021-06-09 20:35 UTC, korcha commented on 07-lection5/02-radio/radio.css
> +    border:3px solid var(--white);
<img width="218" alt="Снимок экрана 2021-06-09 в 23 32 10" src="https://user-images.githubusercontent.com/7526903/121425364-fcd5df80-c97a-11eb-8b40-2df5355e39f2.png">

2021-06-09 20:42 UTC, korcha commented on 07-lection5/03-toggler/toggler.css
> +    width: 26px;
поправила

2021-06-09 20:42 UTC, korcha commented on 07-lection5/03-toggler/toggler.css
> +    top:0;
сделала без отступов

2021-06-09 20:43 UTC, korcha commented on components/tabs/tab.css
> +    width:0px;
сделала

2021-06-09 20:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-10 08:20 UTC, GSemikozov requested changes

2021-06-10 08:20 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    margin-top:20px;
марджины у блоков мы задаем только через родительские элементы, которые могут управлять внешним поведением своих дочерних элементов)

2021-06-10 09:03 UTC, korcha commented on 07-lection5/02-radio/radio.css
> +    margin-top:20px;
Поправила

2021-06-10 09:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-10 09:14 UTC, GSemikozov approved these changes

2021-06-10 09:15 UTC, merged